//
// Created by Oleksandr Fryziuk on 11.02.2020.
//

#ifndef VIRGIL_PUREKIT_CPP_PHECLIENTENROLLACCOUNTRESULT_H
#define VIRGIL_PUREKIT_CPP_PHECLIENTENROLLACCOUNTRESULT_H

class PheClientEnrollAccountResult {

};

#endif //VIRGIL_PUREKIT_CPP_PHECLIENTENROLLACCOUNTRESULT_H
